name: Kotlin CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v1

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Remove FIle
        uses: JesseTG/rm@v1.0.2
        with:
          path: /app/src/main/res/values/secrets.xml
          
      - name: Lint Checker
        run: ./gradlew lint

      - name: Unit Test
        run: ./gradlew testDebugUnitTest

      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports

  generate-apk:
    name: Generate apk
    runs-on: ubuntu-lates
    needs: 
      - build-and-test
    steps:
      - uses: actions/checkout@v1

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Generate apk
        run: ./gradleq assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: build-output
          path: app/build/aoutput/apk/debug/app-debug.apk
